### ISSUE TITLE
Selectable Grid focus indication

### ISSUE THREAD

**Issue by alours** [eureka2/ab-datepicker#25] opened 2017-10-27 17:11 UTC
Greetings. Thank you for working on this project. I think I found an issue with your grid focus indication because in the current version, when focus shifts to the grid, any indication pretty much disappears until you move to another day using the arrow keys.

Using the blue theme, I found the issue (as I see it in the datepicker.css file).  In fact, it seems to be this way in every theme, but each line that should provide focus has...

div.datepicker2-calendar.blue table.datepicker2-grid td.selectable:hover,
div.datepicker2-calendar.blue table.datepicker2-grid td.selectable.focus {
	background-color: #0B6BA8;
	color: #FFF;
	border-color: #3484B7;
}

On the second entry, it ends with "td.selectable.focus" and I think it should end with "td.selectable:focus".  Anyway, that fixed it for me and made the focus pop when switching into the grid itself.  Again, it looks like it is this way throughout the css file, so they probably all need fixing.

**Comment by eureka2** [comment] 2017-12-08 11:14
This is not an error because "focus" is a css class that is added / dynamically deleted in Javascript by this component.

I can not reproduce what you indicate.

Is it the same here: http://eureka2.github.io/ab-datepicker/

**Comment by eureka2** [comment] 2017-12-16 16:32
No answer, I close this issue

**Closed by eureka2** 2017-12-16 16:32 UTC
